/**
 * Dummy data to demo threecharts.
 */
export const demoData = {
  youtubeSubscriber: {
    dimensions: ["country", "language", "category", "subscribeByMe"],
    measures: ["subscriber"],
    labels: ["name"],
    data: [
      {
        name: "channel 1",
        country: "US",
        language: "English",
        category: "Gaming",
        subscriber: 1000000,
        subscribeByMe: true,
      },
      {
        name: "channel 2",
        country: "US",
        language: "Spanish",
        category: "Family",
        subscriber: 500000,
        subscribeByMe: false,
      },
      {
        name: "channel 3",
        country: "Japan",
        language: "Japanese",
        category: "Sports",
        subscriber: 1000000,
        subscribeByMe: true,
      },
      {
        name: "channel 4",
        country: "China",
        language: "Chinese",
        category: "Sports",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 5",
        country: "Korea",
        language: "Korean",
        category: "Gaming",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 6",
        country: "Canada",
        language: "English",
        category: "Music",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 7",
        country: "Mexico",
        language: "Spanish",
        category: "Gaming",
        subscriber: 500000,
        subscribeByMe: false,
      },
      {
        name: "channel 8",
        country: "Japan",
        language: "Japanese",
        category: "Music",
        subscriber: 1000000,
        subscribeByMe: true,
      },
      {
        name: "channel 9",
        country: "US",
        language: "Chinese",
        category: "Sports",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 10",
        country: "US",
        language: "Korean",
        category: "Music",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 11",
        country: "China",
        language: "English",
        category: "Family",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 12",
        country: "Mexico",
        language: "Spanish",
        category: "Movie",
        subscriber: 500000,
        subscribeByMe: false,
      },
      {
        name: "channel 13",
        country: "US",
        language: "Japanese",
        category: "Sports",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 14",
        country: "China",
        language: "Chinese",
        category: "Movie",
        subscriber: 1000000,
        subscribeByMe: true,
      },
      {
        name: "channel 15",
        country: "US",
        language: "Korean",
        category: "Gaming",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 16",
        country: "Canada",
        language: "English",
        category: "Family",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 17",
        country: "US",
        language: "Spanish",
        category: "Gaming",
        subscriber: 500000,
        subscribeByMe: false,
      },
      {
        name: "channel 18",
        country: "Japan",
        language: "English",
        category: "Music",
        subscriber: 1000000,
        subscribeByMe: false,
      },
      {
        name: "channel 19",
        country: "Korea",
        language: "Chinese",
        category: "Family",
        subscriber: 1000000,
        subscribeByMe: true,
      },
      {
        name: "channel 20",
        country: "Korea",
        language: "Korean",
        category: "Music",
        subscriber: 1000000,
        subscribeByMe: true,
      },
    ],
  },
};
